# Generated by Django 4.0.2 on 2022-02-13 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_tag_remove_post_group_id_remove_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='object',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='wefwef'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callback.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callback.tag')),
            ],
        ),
    ]
