# Generated by Django 3.2.12 on 2022-02-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0004_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='https://vk.com'),
            preserve_default=False,
        ),
    ]
