# Generated by Django 3.2.12 on 2022-02-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0005_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
