# Generated by Django 4.0.2 on 2022-02-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0003_remove_post_object_post_text_posttag"),
        ("tg_bot", "0002_remove_user_id_user_joined_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="callback.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tg_bot.user"
                    ),
                ),
            ],
        ),
    ]
