# Generated by Django 4.0.2 on 2022-02-10 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_remove_user_id_alter_user_uuid_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='sfsdf', max_length=100),
            preserve_default=False,
        ),
    ]
